SPR:50 - Se agrega creacion y consulta de socios
monicabajonerodcastro/SportApp pull request #45
Opened 2024-04-07 17:10 UTC by nicolasgomez9

2024-04-07 17:49 UTC, JuanSebastianBecerra approved these changes

2024-04-07 21:31 UTC, monicabajonerodcastro requested changes

2024-04-07 21:31 UTC, monicabajonerodcastro commented on administracion/src/blueprints/administracion.py
> +        return jsonify({'msg' :"Usuario ya esta registrado"}),400
Nico, todos los mensajes que retorna el back no son `msg` sino `description` para que sea uniforme al mostrarlos en el front :)

2024-04-07 21:31 UTC, monicabajonerodcastro commented on administracion/src/comandos/obtener_socio.py
> +class ObtenerSocio(BaseCommand):
Nico, hay que proteger este comando con validación de token para que no quede público y pase por el autorizador.
Mírate un ejemplo en `SportApp/administracion/src/comandos/obtener_planes.py` línea 14

2024-04-07 21:31 UTC, monicabajonerodcastro commented on administracion/src/comandos/obtener_socios.py
> +class ObtenerSocios(BaseCommand):
Igual este, proteger con validación de token ...

2024-04-07 21:31 UTC, monicabajonerodcastro commented on administracion/src/errores/errores.py
> +class MissingRequiredToken(ApiError):
Nico, esta clase sobra, puedes usar `InvalidAuthenticationError(description="No existe token en la solicitud")` en donde uses esta clase

2024-04-07 21:31 UTC, monicabajonerodcastro commented on administracion/src/errores/errores.py
> +class InvalidAuthentication(ApiError):
Igual esta ... puedes hacer lo mismo que el comentario anterior

2024-04-07 21:31 UTC, monicabajonerodcastro commented on administracion/src/errores/errores.py
> +class MissingRequiredField2(ApiError):
Esta tambien sobra ... puedes usar MissingRequiredField(description="Parámetros requeridos") ... incluso puedes enviar qué parámetro es requerido. Miráte un ejemplo en `administracion/src/comandos/asignar_deportista_a_plan.py` línea 20

2024-04-09 02:33 UTC, merged

2024-04-11 03:34 UTC, monicabajonerodcastro reviewed
OK